### ISSUE TITLE
Type check failed in binding to parameter '@seps'

### ISSUE THREAD

**Issue by adaptiveoptics** [retupmoca/P6-Net-SMTP#16]
Can't get Net::SMTP working for the life of me! Tests work. But actually using it... and I've tried so many different ways.

The problem is always Type check failed in binding to parameter '@seps'; expected Positional but got Str ("\r\n")

This is in Net::SMTP::Raw line 11 - method get-response : my $line = $.conn.get

Maybe something weird with \r\n again?

**Comment by ToddAndMargo** [comment]
I am getting:

Type check failed in binding to parameter '@seps'; expected Positional but got Str ("\r\n")

This has become critical for me as it is affecting a security program

**Comment by timo** [comment]
i fixed this in rakudo

the issue only happens when you create a socket, then set its nl-in to a single value, then call get() on it.

the current tests all called get() first, then set nl-in.

This caused the call that initializes the decoder to use the default nl-in for initialization and the call to set nl-in later on finds that the decoder already exists and uses a different code-path to change the line separators.

Anyway, if you want you can also fix this in Net::SMTP by changing [this line](https://github.com/retupmoca/P6-Net-SMTP/blob/master/lib/Net/SMTP.pm6#L34) to set a list rather than just the single string. That will make it work for slightly older rakudos, too.

**Comment by ToddAndMargo** [comment]
The guys on the chat line had me change line #34 
https://github.com/retupmoca/P6-Net-SMTP/blob/master/lib/Net/SMTP.pm6#L34
from
$self.conn.nl-in = "\r\n";
to
$self.conn.nl-in = ("\r\n",);
note the extra comma.
And that go me up and going again.

**Comment by retupmoca** [comment]
Looks like this is resolved in current and recent rakudo; please re-open if I still need to adjust Net::SMTP code.
